name: cbp_conv

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          # build toolchain
          sudo apt-get install -y build-essential make pkg-config
          # libarchive for streaming compressed/tar input
          sudo apt-get install -y libarchive-dev
          # external compressors used by writer for non-tar streams
          sudo apt-get install -y gzip xz-utils bzip2 zstd

      - name: Build
        run: |
          make -j$(nproc)

      - name: Show tool help (sanity)
        run: ./bin/trace2json --help || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests (pytest)
        run: |
          pytest -q

